AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for EventBridge Rule
Resources:
  MYRulefromCFT:
    Type: AWS::Events::Rule
    Properties:
      Name: log
      EventPattern: >-
        {"source":["aws.ec2"],"detail-type":["EC2 Instance State-change
        Notification"],"detail":{"state":["running"]}}
      State: ENABLED
      EventBusName: default
      Targets:
        - Id: TestTarget
          Arn:
            Fn::Sub: >-
              arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/events/custom_eblogs
Parameters: {}
